language: python
python:
  - "2.7"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python tests.py
after_success:
  - coveralls